<a href="https://colab.research.google.com/github/llll121/Introduction-to-ML/blob/main/Week8Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MNIST

## Loading the dataset

In [1]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

## Reshaping the Image Data

In [2]:
X_train = X_train.reshape((60000, 28, 28, 1))
X_train.shape

(60000, 28, 28, 1)

In [3]:
X_test = X_test.reshape((10000, 28, 28, 1))
X_test.shape

(10000, 28, 28, 1)

## Normalizing the Image Data

In [4]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

## Convert Labels to Categorical Data

In [5]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_train.shape

(60000, 10)

In [6]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [7]:
y_test = to_categorical(y_test)
y_test.shape

(10000, 10)

## Creating the Neural Network

In [8]:
from tensorflow.keras.models import Sequential
cnn = Sequential()

## Adding Layers to the Network

In [9]:
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
cnn.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=128, kernel_size=(3, 3), activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Flatten())
cnn.add(Dense(units=128, activation='relu'))
cnn.add(Dense(units=10, activation='softmax'))

## Printing the Model’s Summary

In [10]:
cnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 64)        640       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 64)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 128)       73856     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 128)        0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 3200)              0         
                                                                 
 dense (Dense)               (None, 128)               4

## Compiling the Model

In [11]:
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [12]:
%%time
cnn.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

Epoch 1/5
844/844 [==============================] - 7s 5ms/step - loss: 0.1430 - accuracy: 0.9558 - val_loss: 0.0472 - val_accuracy: 0.9850
Epoch 2/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0433 - accuracy: 0.9863 - val_loss: 0.0379 - val_accuracy: 0.9895
Epoch 3/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0302 - accuracy: 0.9908 - val_loss: 0.0350 - val_accuracy: 0.9897
Epoch 4/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0213 - accuracy: 0.9934 - val_loss: 0.0352 - val_accuracy: 0.9900
Epoch 5/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0167 - accuracy: 0.9947 - val_loss: 0.0280 - val_accuracy: 0.9925
CPU times: user 24.1 s, sys: 3.15 s, total: 27.3 s
Wall time: 41.6 s


## Evaluating the Model

In [13]:
loss, accuracy = cnn.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0288 - accuracy: 0.9906


In [14]:
loss

0.028828684240579605

In [15]:
accuracy

0.9905999898910522

In [16]:
predictions = cnn.predict(X_test)
for index, probability in enumerate(predictions[0]):
    print(f'{index}: {probability:.10%}')

0: 0.0000010860%
1: 0.0000003123%
2: 0.0000221063%
3: 0.0000273112%
4: 0.0000000229%
5: 0.0000008807%
6: 0.0000000005%
7: 99.9999165535%
8: 0.0000004142%
9: 0.0000328120%


# Fashion-MNIST

## Loading the dataset

In [17]:
from tensorflow.keras.datasets import fashion_mnist
(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()

## Reshaping the Image Data

In [18]:
X_train = X_train.reshape((60000, 28, 28, 1))
X_train.shape

(60000, 28, 28, 1)

In [19]:
X_test = X_test.reshape((10000, 28, 28, 1))
X_test.shape

(10000, 28, 28, 1)

## Normalizing the Image Data

In [20]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

## Convert Labels to Categorical Data

In [21]:
y_train = to_categorical(y_train)
y_train.shape

(60000, 10)

In [22]:
y_train[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [23]:
y_test = to_categorical(y_test)
y_test.shape

(10000, 10)

## Creating the Neural Network

In [24]:
from tensorflow.keras.models import Sequential
cnn = Sequential()

## Adding Layers to the Network

In [25]:
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
cnn.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=128, kernel_size=(3, 3), activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Flatten())
cnn.add(Dense(units=128, activation='relu'))
cnn.add(Dense(units=10, activation='softmax'))

## Printing the Model’s Summary

In [26]:
cnn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 26, 26, 64)        640       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 13, 13, 64)       0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 11, 11, 128)       73856     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 5, 5, 128)        0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 3200)              0         
                                                                 
 dense_2 (Dense)             (None, 128)              

## Compiling the Model

In [27]:
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [28]:
%%time
cnn.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

Epoch 1/5
844/844 [==============================] - 5s 5ms/step - loss: 0.4662 - accuracy: 0.8345 - val_loss: 0.3331 - val_accuracy: 0.8805
Epoch 2/5
844/844 [==============================] - 4s 5ms/step - loss: 0.3047 - accuracy: 0.8881 - val_loss: 0.3106 - val_accuracy: 0.8852
Epoch 3/5
844/844 [==============================] - 4s 5ms/step - loss: 0.2561 - accuracy: 0.9072 - val_loss: 0.2874 - val_accuracy: 0.8983
Epoch 4/5
844/844 [==============================] - 4s 5ms/step - loss: 0.2233 - accuracy: 0.9183 - val_loss: 0.2470 - val_accuracy: 0.9070
Epoch 5/5
844/844 [==============================] - 4s 5ms/step - loss: 0.1968 - accuracy: 0.9261 - val_loss: 0.2359 - val_accuracy: 0.9157
CPU times: user 22.3 s, sys: 2.3 s, total: 24.6 s
Wall time: 41.5 s


## Evaluating the Model

In [29]:
loss, accuracy = cnn.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.2430 - accuracy: 0.9134


In [30]:
loss

0.24302539229393005

In [31]:
accuracy

0.9133999943733215

In [32]:
predictions = cnn.predict(X_test)
for index, probability in enumerate(predictions[0]):
    print(f'{index}: {probability:.10%}')

0: 0.0000397275%
1: 0.0001268101%
2: 0.0000587839%
3: 0.0000033103%
4: 0.0000000693%
5: 0.0192540392%
6: 0.0000467085%
7: 0.1518467325%
8: 0.0001506709%
9: 99.8284637928%


# 16.4

## Loading the dataset

In [33]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

## Reshaping the Image Data

In [34]:
X_train = X_train.reshape((60000, 28, 28, 1))
X_train.shape

(60000, 28, 28, 1)

In [35]:
X_test = X_test.reshape((10000, 28, 28, 1))
X_test.shape

(10000, 28, 28, 1)

## Normalizing the Image Data

In [36]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

## Convert Labels to Categorical Data

In [37]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_train.shape

(60000, 10)

In [38]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [39]:
y_test = to_categorical(y_test)
y_test.shape

(10000, 10)

## Creating the Neural Network

In [40]:
from tensorflow.keras.models import Sequential
cnn = Sequential()

## Adding Layers to the Network

In [41]:
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
cnn.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=128, kernel_size=(3, 3), activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Flatten())
cnn.add(Dense(units=10, activation='softmax'))

## Printing the Model’s Summary

In [42]:
cnn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 26, 26, 64)        640       
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 13, 13, 64)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 11, 11, 128)       73856     
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 5, 5, 128)        0         
 2D)                                                             
                                                                 
 flatten_2 (Flatten)         (None, 3200)              0         
                                                                 
 dense_4 (Dense)             (None, 10)               

## Compiling the Model

In [43]:
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [44]:
%%time
cnn.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

Epoch 1/5
844/844 [==============================] - 5s 5ms/step - loss: 0.1719 - accuracy: 0.9485 - val_loss: 0.0497 - val_accuracy: 0.9863
Epoch 2/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0535 - accuracy: 0.9838 - val_loss: 0.0424 - val_accuracy: 0.9880
Epoch 3/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0374 - accuracy: 0.9881 - val_loss: 0.0421 - val_accuracy: 0.9877
Epoch 4/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0276 - accuracy: 0.9915 - val_loss: 0.0369 - val_accuracy: 0.9905
Epoch 5/5
844/844 [==============================] - 4s 5ms/step - loss: 0.0226 - accuracy: 0.9928 - val_loss: 0.0361 - val_accuracy: 0.9897
CPU times: user 21.3 s, sys: 2.21 s, total: 23.5 s
Wall time: 21.2 s


## Evaluating the Model

In [45]:
loss, accuracy = cnn.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0282 - accuracy: 0.9910


In [46]:
loss

0.02816532924771309

In [47]:
accuracy

0.9909999966621399

In [48]:
predictions = cnn.predict(X_test)
for index, probability in enumerate(predictions[0]):
    print(f'{index}: {probability:.10%}')

0: 0.0000000534%
1: 0.0000000256%
2: 0.0000412194%
3: 0.0009139538%
4: 0.0000000002%
5: 0.0000005361%
6: 0.0000000000%
7: 99.9990224838%
8: 0.0000004604%
9: 0.0000185120%


#(2)

## Loading the dataset

In [49]:
from tensorflow.keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

## Reshaping the Image Data

In [50]:
X_train = X_train.reshape((60000, 28, 28, 1))
X_train.shape

(60000, 28, 28, 1)

In [51]:
X_test = X_test.reshape((10000, 28, 28, 1))
X_test.shape

(10000, 28, 28, 1)

## Normalizing the Image Data

In [52]:
X_train = X_train.astype('float32') / 255
X_test = X_test.astype('float32') / 255

## Convert Labels to Categorical Data

In [53]:
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_train.shape

(60000, 10)

In [54]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [55]:
y_test = to_categorical(y_test)
y_test.shape

(10000, 10)

## Creating the Neural Network

In [56]:
from tensorflow.keras.models import Sequential
cnn = Sequential()

## Adding Layers to the Network

In [57]:
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
cnn.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Conv2D(filters=128, kernel_size=(3, 3), activation='relu'))
cnn.add(MaxPooling2D(pool_size=(2, 2)))
cnn.add(Flatten())
cnn.add(Dense(units=4096, activation='relu'))
cnn.add(Dense(units=10, activation='softmax'))

## Printing the Model’s Summary

In [58]:
cnn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 26, 26, 64)        640       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 13, 13, 64)       0         
 2D)                                                             
                                                                 
 conv2d_7 (Conv2D)           (None, 11, 11, 128)       73856     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 5, 5, 128)        0         
 2D)                                                             
                                                                 
 flatten_3 (Flatten)         (None, 3200)              0         
                                                                 
 dense_5 (Dense)             (None, 4096)             

## Compiling the Model

In [59]:
cnn.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

## Training the Model

In [60]:
%%time
cnn.fit(X_train, y_train, epochs=5, batch_size=64, validation_split=0.1)

Epoch 1/5
844/844 [==============================] - 8s 8ms/step - loss: 0.1085 - accuracy: 0.9662 - val_loss: 0.0369 - val_accuracy: 0.9878
Epoch 2/5
844/844 [==============================] - 7s 8ms/step - loss: 0.0365 - accuracy: 0.9886 - val_loss: 0.0365 - val_accuracy: 0.9908
Epoch 3/5
844/844 [==============================] - 7s 8ms/step - loss: 0.0230 - accuracy: 0.9929 - val_loss: 0.0478 - val_accuracy: 0.9875
Epoch 4/5
844/844 [==============================] - 7s 8ms/step - loss: 0.0162 - accuracy: 0.9948 - val_loss: 0.0376 - val_accuracy: 0.9910
Epoch 5/5
844/844 [==============================] - 7s 8ms/step - loss: 0.0146 - accuracy: 0.9950 - val_loss: 0.0333 - val_accuracy: 0.9907
CPU times: user 33.9 s, sys: 2.36 s, total: 36.3 s
Wall time: 35.1 s


## Evaluating the Model

In [61]:
loss, accuracy = cnn.evaluate(X_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0316 - accuracy: 0.9911


In [62]:
loss

0.031648293137550354

In [63]:
accuracy

0.991100013256073

In [64]:
predictions = cnn.predict(X_test)
for index, probability in enumerate(predictions[0]):
    print(f'{index}: {probability:.10%}')

0: 0.0000001032%
1: 0.0000002216%
2: 0.0000153294%
3: 0.0000279302%
4: 0.0000000020%
5: 0.0000006358%
6: 0.0000000000%
7: 99.9999284744%
8: 0.0000001203%
9: 0.0000248594%
